#!/bin/bash
# Complete Voice Detoxification Pipeline Demo

echo "======================================================================"
echo "      Voice Detoxification Complete Pipeline Demo"
echo "======================================================================"
echo ""

PROJECT_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
BUILD_DIR="$PROJECT_ROOT/build"
BIN_DIR="$BUILD_DIR/bin"
APP="$BIN_DIR/voice_detox_app.exe"

# Check if executable exists
if [ ! -f "$APP" ]; then
    echo "❌ Error: Application not found at $APP"
    echo "Please build the project first:"
    echo "  cd build"
    echo "  cmake --build . --config Release"
    echo "  cd .."
    exit 1
fi

echo "✓ Application found: $APP"
echo ""

# Step 1: Check help
echo "Step 1: Display help"
echo "========================================================================"
$APP --help
echo ""

# Step 2: Instructions
echo ""
echo "Step 2: Setup Instructions"
echo "========================================================================"
echo ""
echo "1. Download a Whisper model (choose one):"
echo ""
echo "   Tiny (39MB) - Fast, lower accuracy:"
echo "   wget https://huggingface.co/ggerganov/whisper.cpp/resolve/main/ggml-tiny.en.bin -O models/ggml-tiny.en.bin"
echo ""
echo "   Small (140MB) - Good balance:"
echo "   wget https://huggingface.co/ggerganov/whisper.cpp/resolve/main/ggml-small.bin -O models/ggml-small.bin"
echo ""
echo "   Medium (769MB) - Better accuracy:"
echo "   wget https://huggingface.co/ggerganov/whisper.cpp/resolve/main/ggml-medium.bin -O models/ggml-medium.bin"
echo ""

echo "2. Download a Piper TTS model (choose one, all < 200MB):"
echo ""
echo "   Recommended (High quality, 170MB):"
echo "   wget https://huggingface.co/rhasspy/piper-voices/resolve/main/en/en_US/libritts/en_US-libritts-high.onnx -O models/piper-en_US-libritts-high.onnx"
echo "   wget https://huggingface.co/rhasspy/piper-voices/resolve/main/en/en_US/libritts/en_US-libritts-high.onnx.json -O models/piper-en_US-libritts-high.onnx.json"
echo ""
echo "   Medium Quality (100MB):"
echo "   wget https://huggingface.co/rhasspy/piper-voices/resolve/main/en/en_US/libritts/en_US-libritts-medium.onnx -O models/piper-en_US-libritts-medium.onnx"
echo "   wget https://huggingface.co/rhasspy/piper-voices/resolve/main/en/en_US/libritts/en_US-libritts-medium.onnx.json -O models/piper-en_US-libritts-medium.onnx.json"
echo ""

echo "3. Install Python dependencies for Piper TTS:"
echo "   pip install piper-tts"
echo ""

echo "4. Place your audio file:"
echo "   cp your_audio.mp3 tests/inputs/"
echo ""

echo "5. Run the complete pipeline:"
echo "   $APP models/ggml-small.bin tests/inputs/your_audio.mp3 ffmpeg --output clean.wav"
echo ""

echo "======================================================================"
echo "Features Available:"
echo "======================================================================"
echo ""
echo "✓ Stage 1: Speech-to-Text (Whisper STT)"
echo "  Convert audio in any format to text"
echo ""
echo "✓ Stage 2: Toxicity Detection & Removal"
echo "  Detect harmful content and clean the text"
echo ""
echo "✓ Stage 3: Text-to-Speech (Piper TTS)"
echo "  Convert clean text back to audio"
echo ""
echo "✓ Stage 4: Voice Characteristic Restoration"
echo "  Restore original speaker's voice characteristics"
echo ""

echo "======================================================================"
echo "Command Examples:"
echo "======================================================================"
echo ""
echo "# Basic usage - help"
echo "$APP --help"
echo ""
echo "# Full pipeline with default settings"
echo "$APP models/ggml-small.bin tests/inputs/audio.mp3"
echo ""
echo "# Censor toxic words instead of replacing"
echo "$APP --censor-only models/ggml-small.bin tests/inputs/audio.mp3"
echo ""
echo "# Save output to specific file"
echo "$APP --output my_clean_audio.wav models/ggml-small.bin tests/inputs/audio.mp3"
echo ""
echo "# Skip TTS (only detect and remove toxic text)"
echo "$APP --skip-tts models/ggml-small.bin tests/inputs/audio.mp3"
echo ""
echo "# Skip voice restoration (faster, but less natural)"
echo "$APP --skip-voice-restore models/ggml-small.bin tests/inputs/audio.mp3"
echo ""

echo "======================================================================"
echo "Model Download Sizes (All < 4GB):"
echo "======================================================================"
echo ""
echo "Whisper Models:"
echo "  - ggml-tiny.bin      39 MB"
echo "  - ggml-small.bin    140 MB  (recommended)"
echo "  - ggml-medium.bin   769 MB"
echo ""
echo "Piper TTS Models (all < 200MB):"
echo "  - libritts-high     170 MB  (best quality)"
echo "  - libritts-medium   100 MB  (good balance)"
echo "  - glow-tts           80 MB  (fastest)"
echo ""

echo "======================================================================"
echo "Supported Audio Formats:"
echo "======================================================================"
echo ""
echo "✓ MP3       ✓ WAV       ✓ M4A       ✓ FLAC"
echo "✓ OGG       ✓ AAC       ✓ WMA"
echo ""

echo "======================================================================"
echo "Processing Flow:"
echo "======================================================================"
echo ""
echo "1. Input Audio (MP3, WAV, etc.)"
echo "   ↓ [ffmpeg] Decode to 16kHz mono WAV"
echo "2. [Whisper] Speech-to-Text Transcription"
echo "   ↓ 'This is damn good... you idiot'"
echo "3. [Toxicity Detector] Analyze for harmful content"
echo "   ↓ Found: 'damn' (LOW), 'idiot' (HIGH)"
echo "4. [Text Detoxifier] Replace or censor"
echo "   ↓ 'This is darn good... you fool'"
echo "5. [Piper TTS] Convert to speech"
echo "   ↓ Clean audio with neutral voice"
echo "6. [Voice Converter] Apply original voice characteristics"
echo "   ↓ Clean audio with original voice tone"
echo "7. Output Audio (WAV format)"
echo ""

echo "======================================================================"
echo "For more details, see: README.md, GETTING_STARTED.md"
echo "======================================================================"
